version: "3"
services: 
    proxy:
        build: 
            context: ./Proxy
            dockerfile: Dockerfile
        ports: 
            - "127.0.01:8080:80"
        restart: always
    client:
        build:
            context: ./UI
            dockerfile: Dockerfile
        ports: 
            - "9000:80"
    api:
        build: 
            context: ./ArchitectureRefactoringHelper
            dockerfile: Dockerfile
        ports: 
            - "5000:80"